# Generated by Django 5.0.6 on 2024-05-15 12:26

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='default_avatar.jpg', upload_to='profiles'),
        ),
    ]
